/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  networksSidebar: [{ type: 'autogenerated', dirName: 'networks' }],
  standardsSidebar: [
    'standards/introduction',
    'standards/erc725',
    'standards/standard-types',
    'standards/event-reference',
    { type: 'html', value: '<hr/>', defaultStyle: false }, // -----
    {
      type: 'category',
      label: '🗄️ Metadata',
      items: [{ type: 'autogenerated', dirName: 'standards/metadata' }],
    },
    {
      type: 'category',
      label: '🔐 Ownership & Access Control',
      items: [{ type: 'autogenerated', dirName: 'standards/access-control' }],
    },
    {
      type: 'category',
      label: '🆙 Accounts & Interactions',
      items: [{ type: 'autogenerated', dirName: 'standards/accounts' }],
    },
    {
      type: 'category',
      label: '🪙 Tokens & 🖼️ NFTs',
      items: [{ type: 'autogenerated', dirName: 'standards/tokens' }],
    },
    {
      type: 'category',
      label: '🏭 Factories',
      items: [{ type: 'autogenerated', dirName: 'standards/factories' }],
    },
  ],
  learnSidebar: [
    'learn/overview',
    'learn/benefits-lukso-standards',
    'learn/getting-started',
    {
      type: 'category',
      label: '🔀 Migrate to LUKSO',
      items: [
        {
          type: 'autogenerated',
          dirName: 'learn/migrate',
        },
      ],
    },
    { type: 'html', value: '<hr/>', defaultStyle: false }, // -----
    {
      type: 'category',
      label: '🆙 Universal Profile',
      items: [
        {
          type: 'autogenerated',
          dirName: 'learn/universal-profile',
        },
      ],
    },
    {
      type: 'category',
      label: '🖼️ Tokens & NFTs (LSP7/8)',
      items: [
        {
          type: 'autogenerated',
          dirName: 'learn/digital-assets',
        },
      ],
    },
    {
      type: 'category',
      label: '🧃 Grid & Mini-Apps',
      items: [
        {
          type: 'autogenerated',
          dirName: 'learn/mini-apps',
        },
      ],
    },
    { type: 'html', value: '<hr/>', defaultStyle: false }, // -----

    // Hide Vault guides for now, as LSP9 standard is still draft and will be re-worked
    // {
    //   type: 'category',
    //   label: '🔑 Vault',
    //   items: [
    //     {
    //       type: 'autogenerated',
    //       dirName: 'learn/vault',
    //     },
    //   ],
    // },
    {
      type: 'category',
      label: '🗺️ Other Guides',
      items: [
        {
          type: 'autogenerated',
          dirName: 'learn/other-guides',
        },
      ],
    },
    'learn/standard-detection',
    'learn/concepts',
  ],
  contractsSidebar: [
    'contracts/introduction',
    'contracts/deployed-contracts',
    // divider for the main smart contracts
    { type: 'html', value: '<hr/>', defaultStyle: false },
    {
      type: 'autogenerated',
      dirName: 'contracts/overview',
    },
    // divider for the Contracts ABI and Libraries Technical references
    { type: 'html', value: '<hr/>', defaultStyle: false },
    {
      type: 'category',
      label: '📑 ABI Technical Reference',
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'contracts/contracts',
        },
      ],
    },
    {
      type: 'category',
      label: '📒 Solidity Libraries',
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'contracts/libraries',
        },
      ],
    },
    // divider for the Libraries Technical references
    { type: 'html', value: '<hr/>', defaultStyle: false },
    'contracts/interface-ids',
    'contracts/type-ids',
    {
      type: 'link',
      label: 'Audits',
      href: 'https://github.com/lukso-network/lsp-smart-contracts/tree/main/audits',
    },
  ],
  toolsSidebar: [{ type: 'autogenerated', dirName: 'tools' }],
  faqSidebar: [{ type: 'autogenerated', dirName: 'faq' }],
};
